version: "3"

services:

  backend:
    build: ./backend
    container_name: backend
    command: ['./start.sh']
    ports:
      - "10004:10004"
    depends_on:
      - syncslot_db
    networks:
      - syncslot_network

  syncslot_db:
    image: postgres:17.1
    container_name: "syncslot_db"
    hostname: 'db'
    volumes:
      - syncslot_data:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_DB: syncslot_db
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
    ports:
      - "5432:5432"
    networks:
      - syncslot_network

  maildev:
    image: maildev/maildev
    environment:
      - TZ=Europe/Moscow
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "8080:1080"
      - "1025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    networks:
      - syncslot_network

volumes:
  syncslot_data:

networks:
  syncslot_network:
    driver: bridge
